import { cn } from "@/lib/utils";
import type { ReactNode } from "react";
import { Button } from "./button";

interface AIOutputBlockProps {
  label?: string;
  children: ReactNode;
  showCursor?: boolean;
  foot?: ReactNode;
  className?: string;
}

function AIOutputBlock({
  label = "Generated by ContentOS AI",
  children,
  showCursor = false,
  foot,
  className,
}: AIOutputBlockProps) {
  return (
    <div className={cn("ai-block", className)}>
      <div className="ai-block-head">
        <span className="ai-label">
          <span className="ai-star">✦</span>
          {label}
        </span>
        <Button variant="ghost" size="sm">
          ⎘ Copy
        </Button>
      </div>
      <div className="ai-block-body">
        {children}
        {showCursor && <span className="ai-cursor" />}
      </div>
      {foot && <div className="ai-block-foot">{foot}</div>}
    </div>
  );
}

export { AIOutputBlock, type AIOutputBlockProps };
