export const SERIES_FORMATS = [
  {
    id: "countdown",
    name: "Numbered Countdown / Challenge",
    icon: "▤",
    description: "Fixed-episode count with a declared finish line — Lesson 1 of 30, Day 14 of 259",
    steps: ["HOOK", "STAMP", "PROMISE", "UNIT", "PROOF", "LOOP"],
    templates: [
      { step: "HOOK", text: 'Lead with stakes, not the count. "The most [adjective] mistake I made was [behavior]."' },
      { step: "STAMP", text: 'Locate the episode. "Lesson [N] of [total]."' },
      { step: "PROMISE", text: 'Re-sell the journey. "Welcome to [series name], a [duration] series where I teach you [outcome]."' },
      { step: "UNIT", text: 'One complete idea. "Today we\'re talking about [topic], because [why now]."' },
      { step: "PROOF", text: 'Validate it\'s universal. "[Stat]% of people [shared problem]."' },
      { step: "LOOP", text: 'Save + return. "Screenshot this. Next lesson\'s tomorrow."' },
    ],
    secretSauce: "The count creates an open loop the algorithm rewards daily. Lead with the emotional hook, not the number. Each episode stands alone AND compounds.",
  },
  {
    id: "progress",
    name: "Progress Journey",
    icon: "↗",
    description: "Open-ended mission documentation — day count toward a big goal until I hit X",
    steps: ["DAY-STAMP HOOK", "VALUE DROP", "STAKES & HISTORY", "PROOF OF PROGRESS", "THE TEASE", "PARTICIPATION CTA"],
    templates: [
      { step: "DAY-STAMP HOOK", text: 'Anchor in the mission. "Today is day [number] of [mission]."' },
      { step: "VALUE DROP", text: 'Standalone reason to watch. "[Quick tip or result the viewer can use today]."' },
      { step: "STAKES & HISTORY", text: 'Remind why it matters. "For [number] years, [thing] has been [state]."' },
      { step: "PROOF OF PROGRESS", text: 'Show today moved the needle. "Today I [specific action completed]."' },
      { step: "THE TEASE", text: 'Pull viewers to next. "I\'m gearing up for something [epic descriptor]."' },
      { step: "PARTICIPATION CTA", text: 'Convert to returning viewers. "Follow to see [outcome] come to life."' },
    ],
    secretSauce: "The day number IS the hook — most prominent visual in the first 2 seconds. Pick a mission with a real-world finish line outside your control for genuine suspense.",
  },
  {
    id: "educational",
    name: "Recurring Educational Segment",
    icon: "◈",
    description: "No story arc, no fixed end — same format, fresh standalone tip every episode",
    steps: ["SIGNATURE OPEN", "SERIES TAG", "PAYLOAD", "RESULT-FIRST PROOF", "THE HOW", "RETURN LOOP"],
    templates: [
      { step: "SIGNATURE OPEN", text: 'Trigger instant recognition. "[Recurring stock phrase], part [number]."' },
      { step: "SERIES TAG", text: 'Re-announce the series. "Welcome back to [series name]."' },
      { step: "PAYLOAD", text: 'Name today\'s tip. "Today we\'re [planning/fixing/hacking] your [topic]."' },
      { step: "RESULT-FIRST PROOF", text: 'Show outcome before the how. "You can [impressive result]. Here\'s what I mean..."' },
      { step: "THE HOW", text: 'Low-friction steps. "Go to [location] and [action]."' },
      { step: "RETURN LOOP", text: 'Close the habit loop. "Save this and come back for [next episode]."' },
    ],
    secretSauce: "A fixed format signature is the moat — same intro, banner, layout every time. Self-contained value per episode with no prerequisite to watch.",
  },
  {
    id: "case-study",
    name: "Case Study / Breakdown",
    icon: "◎",
    description: "One lens, fresh subject each episode — dissecting why something is winning or losing",
    steps: ["SUBJECT REVEAL", "PROOF DROP", "LENS", "BREAKDOWN BEAT", "CONTRARIAN TURN", "SERIES CTA"],
    templates: [
      { step: "SUBJECT REVEAL", text: 'Name the case study. "This is [subject] and here\'s why they\'re [winning/losing] at [area]."' },
      { step: "PROOF DROP", text: 'Validate with a number. "After [metric/result], here\'s how they did it."' },
      { step: "LENS", text: 'State the framework. "There are [number] things they\'re doing really well."' },
      { step: "BREAKDOWN BEAT", text: 'Dissect a factor. "Number one, they [specific tactic] and that signals [meaning]."' },
      { step: "CONTRARIAN TURN", text: 'Subvert the assumption. "Everyone thinks [belief], but actually [reality]."' },
      { step: "SERIES CTA", text: 'Loop to next. "I break down [series name] every week. Comment who I should do next."' },
    ],
    secretSauce: "Make the FRAMEWORK the brand, not the subject. Take polarizing stances and invite disagreement — comments compound the outlier.",
  },
  {
    id: "docuseries",
    name: "Docuseries",
    icon: "▷",
    description: "Personality-driven chapters of your own arc — signature ritual, recurring host, real story",
    steps: ["COLD OPEN", "STAKES HOOK", "SHOW ID + RECAP", "EPISODE PROMISE", "LIVED-EXPERIENCE BODY", "OPEN-LOOP OUTRO"],
    templates: [
      { step: "COLD OPEN", text: 'Re-establish the show. "Welcome back to [show name]."' },
      { step: "STAKES HOOK", text: 'Justify emotionally. "Now that [reality] is so bad, I might as well [risky pivot]..."' },
      { step: "SHOW ID + RECAP", text: 'Anchor in the arc. "This is [series name], where I share [premise]."' },
      { step: "EPISODE PROMISE", text: 'Set today\'s payload. "Here are [number] ways I\'m going to [goal]."' },
      { step: "LIVED-EXPERIENCE BODY", text: 'Prove with your story. "[Number]: [theme]. For me, that looked like [personal example]."' },
      { step: "OPEN-LOOP OUTRO", text: 'Guarantee the return. "New episode every [day]. Same time, same place."' },
    ],
    secretSauce: "A repeatable signature opening is the show's title card. Vulnerability is the currency — real failure as the throughline makes the show feel earned.",
  },
  {
    id: "skit",
    name: "Skit Universe",
    icon: "⌘",
    description: "Recurring characters in a fixed world — same comedic engine, fresh situation each episode",
    steps: ["SETUP", "PROVOCATION", "ENGINE BEAT", "ESCALATION", "REVEAL", "BUTTON"],
    templates: [
      { step: "SETUP", text: 'Re-establish the world. "[Recurring character] walks into [recurring setting] and [inciting line]."' },
      { step: "PROVOCATION", text: 'Drop the tension line. "[Character] says \'[provocative/ambiguous statement].\'"' },
      { step: "ENGINE BEAT", text: 'Run the signature contrast. "[Character] frames [trivial thing] as \'[inflated version].\'"' },
      { step: "ESCALATION", text: 'Repeat the engine bigger. "[Other character] doubles down with \'[even more absurd version].\'"' },
      { step: "REVEAL", text: 'Snap to mundane truth. "Turns out [character] just meant \'[plain explanation].\'"' },
      { step: "BUTTON", text: 'Tag and reset. "[Character] exits with \'[in-character twist line].\'"' },
    ],
    secretSauce: 'The comedic ENGINE is fixed, not the joke. Deadpan protagonist + high-energy reactors. Repetition with escalation trains viewers to anticipate the reveal.',
  },
] as const;

export type SeriesFormatId = (typeof SERIES_FORMATS)[number]["id"];
