"""
Export tool — converts text content to PDF file.

Usage:
    python export_pdf.py --content "Your script content here..." --output script.pdf
    python export_pdf.py --input input.txt --output output.pdf

Dependencies:
    pip install fpdf2
"""

import os
import argparse
from typing import Optional

from fpdf import FPDF


class ContentPDF(FPDF):
    def header(self):
        self.set_font("Helvetica", "B", 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 8, "Generated by ContentOS AI", align="C", new_x="LMARGIN", new_y="NEXT")
        self.line(10, 14, 200, 14)
        self.ln(4)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, f"Page {self.page_no()}/{{nb}}", align="C")


def export_pdf(
    content: str,
    output_path: str,
    title: str = "ContentOS Export",
) -> str:
    pdf = ContentPDF()
    pdf.alias_nb_pages()
    pdf.add_page()
    pdf.set_font("Helvetica", "B", 16)
    pdf.cell(0, 12, title, new_x="LMARGIN", new_y="NEXT")
    pdf.ln(4)

    pdf.set_font("Helvetica", "", 11)
    pdf.multi_cell(0, 6, content)

    pdf.output(output_path)
    return os.path.abspath(output_path)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Export content to PDF")
    parser.add_argument("--content", help="Text content to export")
    parser.add_argument("--input", help="Input file path (alternative to --content)")
    parser.add_argument("--output", required=True, help="Output PDF path")
    parser.add_argument("--title", default="ContentOS Export", help="Document title")

    args = parser.parse_args()

    if args.input:
        with open(args.input, "r", encoding="utf-8") as f:
            content = f.read()
    elif args.content:
        content = args.content
    else:
        raise ValueError("Provide either --content or --input")

    path = export_pdf(content=content, output_path=args.output, title=args.title)
    print(f"PDF exported to: {path}")
